// Values match Monaco's actual registered language ids (confirmed against
// node_modules/monaco-editor/esm/vs/languages/definitions/*/register.js), not just
// common naming — e.g. Monaco's shell-script id is "shell", not "bash".
export const CODE_LANGUAGES = [
  { value: "javascript", label: "JavaScript" },
  { value: "typescript", label: "TypeScript" },
  { value: "python", label: "Python" },
  { value: "java", label: "Java" },
  { value: "c", label: "C" },
  { value: "cpp", label: "C++" },
  { value: "csharp", label: "C#" },
  { value: "go", label: "Go" },
  { value: "rust", label: "Rust" },
  { value: "php", label: "PHP" },
  { value: "ruby", label: "Ruby" },
  { value: "swift", label: "Swift" },
  { value: "kotlin", label: "Kotlin" },
  { value: "scala", label: "Scala" },
  { value: "dart", label: "Dart" },
  { value: "elixir", label: "Elixir" },
  { value: "clojure", label: "Clojure" },
  { value: "objective-c", label: "Objective-C" },
  { value: "perl", label: "Perl" },
  { value: "lua", label: "Lua" },
  { value: "r", label: "R" },
  { value: "sql", label: "SQL" },
  { value: "html", label: "HTML" },
  { value: "css", label: "CSS" },
  { value: "scss", label: "SCSS" },
  { value: "less", label: "Less" },
  { value: "json", label: "JSON" },
  { value: "yaml", label: "YAML" },
  { value: "xml", label: "XML" },
  { value: "markdown", label: "Markdown" },
  { value: "graphql", label: "GraphQL" },
  { value: "hcl", label: "HCL / Terraform" },
  { value: "dockerfile", label: "Dockerfile" },
  { value: "shell", label: "Shell" },
  { value: "powershell", label: "PowerShell" },
  { value: "bat", label: "Batch" },
  { value: "plaintext", label: "Plain Text" },
] as const;

export type CodeLanguage = (typeof CODE_LANGUAGES)[number]["value"];
